---
kind: pipeline
name: front-end

steps:
- name: install dependencies
  image: node:8.10
  commands:
  - npm i

- name: fmt
  image: node:8.10
  commands:
  - npm run prettier:check

- name: lint
  image: node:8.10
  commands:
  - npm run lint:ts

- name: build
  image: node:8.10
  commands:
  - npm run build
